### ISSUE TITLE
Automation scripts need to be able to run on the University's servers

### ISSUE THREAD

**Issue by karim2506** [merekorlowski/taskwipe#5]

**Comment by preciousO** [comment]
@merekorlowski  @karim2506   what's this about?

**Comment by karim2506** [comment]
@Opeoluwa112  these were part of the issues that were written in the beginning of the semester (I wrote it, didn't know exactly what an "issue" meant back then).
Basically it means that we have to eventually make sure that the automation scripts can be run on the uOttawa environment.

I don't know if we want to keep it.
